# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Cache file path
export XDG_CACHE_HOME=$HOME/.cache
export ZCOMPDUMP=$XDG_CACHE_HOME/.zcompdump
export HISTFILE=$XDG_CACHE_HOME/.zsh_history
export XAUTHORITY=$XDG_CACHE_HOME/.Xauthority
export LESSHISTFILE=$XDG_CACHE_HOME/.lesshst
export PYTHONHISTFILE=$XDG_CACHE_HOME/.python_history

# Language
# Golang
export GO111MODULE=on
# export GOPROXY=https://goproxy.cn,direct
export GOPROXY=https://goproxy.io,direct
export GOSUMDB=sum.golang.google.cn
export GOPATH="$HOME/.local/go"
export GOBIN="$GOPATH/bin"
export PATH="$GOBIN:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# .Net
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

# Java
#export JAVA_HOME="/usr/local/jdk1.8.0_311"
#export PATH="$JAVA_HOME/bin:$PATH"
#export M2_HOME="/usr/local/apache-maven-3.8.3"
#export PATH="$M2_HOME/bin:$PATH"
# Jenv
#export PATH="$HOME/.jenv/bin:$PATH"
#if command -v jenv >/dev/null 2>&1; then
#    eval "$(jenv init -)"
#fi

# Pyenv with github
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init --path)"
    eval "$(pyenv virtualenv-init -)"
fi

# NVM
export NVM_DIR="$HOME/.nvm"
export npm_config_cache=${XDG_CACHE_HOME:-$HOME/.cache}/.npm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# DWM script
export TERMINAL="st"
export EDITOR="nvim"

# Custom
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.bin/tools:$PATH"
export PATH="$HOME/.bin/dwm.script:$PATH"
export PATH="$HOME/.bin/rainbarf:$PATH"
export PATH="$HOME/.bin/install:$PATH"

# Default programs:
export RANGER_LOAD_DEFAULT_RC=false

# Wget
export WGETRC=$HOME/.config/wget/wgetrc

# Fix https://github.com/imhuso/cunzhi Open a blank bug
export WEBKIT_DISABLE_DMABUF_RENDERER=1
