# golang
export GO111MODULE=on
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
#export GOPROXY=https://mirrors.aliyun.com/goproxy/

# Pyenv with github
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYENV_ROOT=$HOME/.pyenv
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# ranger
export RANGER_LOAD_DEFAULT_RC=false

#PATH
PATH=$HOME/my.scripts:$GOPATH/bin:$PYENV_ROOT/bin:$PATH

