# my.scripts
export PATH="$HOME/my.scripts:$PATH"

# rust
#export PATH="$HOME/.cargo/bin:$PATH"

# golang
export GO111MODULE=on
export GOROOT="$HOME/.local/go"
export GOBIN="$GOROOT/bin"
export GOPATH="$HOME/my.codes/go"
export PATH="$GOROOT/bin:$PATH"
export GOPROXY="https://goproxy.io,direct"

# Pyenv with github
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init --path)"
    eval "$(pyenv virtualenv-init -)"
fi

# ranger
export RANGER_LOAD_DEFAULT_RC=false

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="google-chrome-stable"
