# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="robbyrussell"
#ZSH_THEME="ys"
#ZSH_THEME="random"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    history
    history-substring-search
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration
source ~/.config/zsh/p10k.zsh
source ~/.config/zsh/cursor.zsh
source ~/.config/zsh/plugin-settings.zsh
source ~/.config/zsh/aliases.zsh
#go get -u github.com/tanx-code/autojump-go
source ~/.config/zsh/autojump-go.zsh

# Other program
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/share/nvm/init-nvm.sh ] && source /usr/share/nvm/init-nvm.sh
