# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="robbyrussell"
ZSH_THEME="ys"
#ZSH_THEME="random"
#ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    history
    history-substring-search
    zsh-autosuggestions
    zsh-syntax-highlighting
    autojump
)

source $ZSH/oh-my-zsh.sh

# User configuration
source ${HOME}/.config/zsh/aliases.zsh
source ${HOME}/.config/zsh/plugin-settings.zsh
source ${HOME}/.config/zsh/cursor.zsh
source ${HOME}/.config/zsh/p10k.zsh
